---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: pinentry-keyring

env:
  - CGO_ENABLED=0

builds:
  - binary: pinentry-keyring
    main: main.go
    goos:
      - linux
    goarch:
      - arm64
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s

archives:
  - formats: ["binary"]

changelog:
  disable: true
release:
  disable: true
