---
name: CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Use to set tag, default: rolling"
        type: string
        default: "rolling"
        required: false
  workflow_call:
    inputs:
      tag:
        description: "Use to set tag, default: rolling"
        type: string
        default: "rolling"
        required: false
  push:
    branches: ["main"]
    paths:
      - "go.mod"
      - "go.sum"
      - "*.go"
      - "**/*.go"
  pull_request:
    branches: ["main"]
    paths:
      - "go.mod"
      - "go.sum"
      - "*.go"
      - "**/*.go"
      - ".github/workflows/ci.yaml"
      - "hack/*.sh"
  merge_group:
    branches: ["main"]

jobs:
  lint:
    uses: heathcliff26/ci/.github/workflows/golang-lint.yaml@main
    permissions:
      contents: read

  gosec:
    uses: heathcliff26/ci/.github/workflows/golang-gosec.yaml@main
    permissions:
      contents: read
      security-events: write

  unit-tests:
    uses: heathcliff26/ci/.github/workflows/golang-unit-tests.yaml@main
    permissions:
      contents: read
    with:
      coveralls: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}

  validate:
    uses: heathcliff26/ci/.github/workflows/golang-build.yaml@main
    permissions:
      contents: read
    with:
      cache: false
      cmd: "make validate"

  build-binary:
    uses: heathcliff26/ci/.github/workflows/golang-build.yaml@main
    permissions:
      contents: read
    with:
      release: "${{ github.event_name == 'pull_request' && 'devel' || inputs.tag == '' && 'rolling' || inputs.tag }}"
      artifact: "dist/pinentry-keyring*"
      artifact-name: "pinentry-keyring"
      cmd: "make release"
    secrets: inherit
